### ISSUE TITLE
Fix deprecated express uses

### ISSUE THREAD

**Issue by copperwall** [iFixit/pulldasher#74]
There were warnings last time pulldasher started up about some deprecated uses of express middleware.

```
express-session deprecated undefined resave option; provide resave option at app.js:37:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at app.js:37:9
express deprecated req.param(name): Use req.params, req.body, or req.query instead at controllers/githubHooks.js:22:24
```

The first two just want a specified value instead of using the default, the second wants us to stop using `param` because it checks for the value in the query string, route match, and request body.

**Comment by copperwall** [comment]
Fixed by #77
